### ISSUE TITLE
Errata 1 gaat niet over VirtualPC maar over VirtualBox

### ISSUE THREAD

**Issue by wullumpie** [botris/ict-security#1]
Hoi Boris,

De referentie in het eerste erratum naar de ondersteuning van VirtualBox van USB lijkt me niet van toepassing op de tekst in het boek. Daarin schrijf je dat VirtualPC geen USB-ondersteuning heeft.

Met vriendelijke groet,
Willem de Vries

**Comment by botris** [comment]
Bedankt, ik heb de tekst verder verduidelijkt. Virtual PC had geheel niet in de tekst moeten staan.
