### ISSUE TITLE
Tools hoofdstuk 7 niet meer beschikbaar

### ISSUE THREAD

**Issue by jvzetten** [botris/ict-security#2]
md5sum wat nodig is voor het uitvoeren van practicum 7.4 en 7.7 is niet meer beschikbaar.
Kunnen deze toegevoegd worden of is er een bruikbaar alternatief?

**Comment by botris** [comment]
De tools staan allemaal op https://www.ict-security-boek.nl/hoofdstuk7
Uitgaande van de laatste druk (2020) uiteraard.
Welke specifieke tool mis je daar?

**Comment by jvzetten** [comment]
Wij kunnen MD5SUM daar niet vinden.

**Comment by botris** [comment]
De tool MD5SUM wordt niet meer gebruikt in de 2020 druk en is vervangen door CertUtil.
Er zijn ook online tools te vinden die MD5 checksums kunnen genereren / verifieren.
